dist: trusty
sudo: required
language: generic
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7
            - clang-5.0
      env:
        - MATRIX_EVAL="export COMPILER_NAME=clang++ && export CXX=clang++-5.0"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7-multilib
      env:
        - MATRIX_EVAL="export COMPILER_NAME=g++ && export CXX=/usr/bin/g++-7"
git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - eval "${MATRIX_EVAL}"
  - if [ "$COMPILER_NAME" = "g++" ]; then
      sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++ && g++ -v;
    elif [ "$COMPILER_NAME" = "clang++" ]; then
      clang++ -v;
    fi
script:
  - chmod +x build.sh
  - ./build.sh
after_success:
  - if [ "$COMPILER_NAME" = "g++" ]; then
      bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports";
    fi
notifications:
  email: false
