dist: trusty
sudo: required
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="COMPILER_NAME=clang++ && CC=clang-5.0 && CXX=clang++-5.0"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7-multilib
            - g++-7-multilib
      env:
        - MATRIX_EVAL="COMPILER_NAME=g++ && CC=/usr/bin/gcc-7 && CXX=/usr/bin/g++-7"
git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
before_script:
  - eval "${MATRIX_EVAL}"
  - if [ "$COMPILER_NAME" = "g++" ]; then
      sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc && sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++ && g++ -v;
    elif [ "$COMPILER_NAME" = "clang++" ]; then
      clang++ -v;
    fi
  - export TRIES=5;
script:
  - sudo ./build.sh
notifications:
  email: false
