var searchData=
[
  ['l1regularizationpenalty',['L1RegularizationPenalty',['../classcattle_1_1_l1_regularization_penalty.html#a45d221d19d3f1f4ce956372238267ac2',1,'cattle::L1RegularizationPenalty']]],
  ['l2regularizationpenalty',['L2RegularizationPenalty',['../classcattle_1_1_l2_regularization_penalty.html#a5c3f3d80a41aa131d706a3f4536c70ff',1,'cattle::L2RegularizationPenalty']]],
  ['leakyreluactivationlayer',['LeakyReLUActivationLayer',['../classcattle_1_1_leaky_re_l_u_activation_layer.html#a4e4a5aeb1738750b50c9761e9db9a6d7',1,'cattle::LeakyReLUActivationLayer']]],
  ['lecunweightinitialization',['LeCunWeightInitialization',['../classcattle_1_1_le_cun_weight_initialization.html#abb67314bc4ef9fb180c01b18435d462f',1,'cattle::LeCunWeightInitialization']]],
  ['lesser_5for_5falmost_5fequal',['lesser_or_almost_equal',['../classcattle_1_1_utils.html#a3dcde6137028bc88708d0b159bd0d0a7',1,'cattle::Utils']]],
  ['lstmneuralnetwork',['LSTMNeuralNetwork',['../classcattle_1_1_l_s_t_m_neural_network.html#ade4fd4a2dc354489384d2ace3be953ed',1,'cattle::LSTMNeuralNetwork::LSTMNeuralNetwork(KernelPtr&lt; Scalar, Rank &gt; input_forget_kernel, KernelPtr&lt; Scalar, Rank &gt; output_forget_kernel, KernelPtr&lt; Scalar, Rank &gt; input_write_kernel, KernelPtr&lt; Scalar, Rank &gt; output_write_kernel, KernelPtr&lt; Scalar, Rank &gt; input_candidate_kernel, KernelPtr&lt; Scalar, Rank &gt; output_candidate_kernel, KernelPtr&lt; Scalar, Rank &gt; input_read_kernel, KernelPtr&lt; Scalar, Rank &gt; output_read_kernel, ActivationPtr&lt; Scalar, Rank &gt; forget_act, ActivationPtr&lt; Scalar, Rank &gt; write_act, ActivationPtr&lt; Scalar, Rank &gt; candidate_act, ActivationPtr&lt; Scalar, Rank &gt; state_act, ActivationPtr&lt; Scalar, Rank &gt; read_act, OutputSeqSizeFunc output_seq_size_func, bool stateful=false, bool mul_int=false, bool reversed=false, bool foremost=true)'],['../classcattle_1_1_l_s_t_m_neural_network.html#ad3579d6c5889109b509c9f28fc820d72',1,'cattle::LSTMNeuralNetwork::LSTMNeuralNetwork(const Self &amp;network)'],['../classcattle_1_1_l_s_t_m_neural_network.html#a72c41b863276572146581e51e32a36c2',1,'cattle::LSTMNeuralNetwork::LSTMNeuralNetwork(Self &amp;&amp;network)']]]
];
